### ISSUE TITLE
My glider has an engine but the ENL is not evaluated

### ISSUE THREAD

**Issue by UniformPapa** [weglide/bugtracker#119]
**Describe the bug**
The engine noise level is not evaluated to limit the scoring window although the glider "LS 10-st 18m" does have an engine.
 ("t" in type designation)

**To Reproduce**
1. During flight upload, I select my type of glider "LS 10-st 18m".
2. However the message "Flugzeug ohne Motor ausgewählt, wechsel zu einem Flugzeug mit Motor um potentielle Motorläufe zu sehen." is displayed. This is not correct.

**Expected behavior**
"LS 10-st 18m" shall be treated like other gliders with engine. I have tested the same igc-file with "Discus 2bt" and there the behavior is o.k.

**Screenshots**
n/a

**Device (please complete the following information):**
 - personal computer (intel processor)
 - Windows 10
 - Google Chrome

**Comment by samuel-git** [comment]
Thanks, this is a mistake in our glider database. We will fix it.
Here is more information about the types: https://de.wikipedia.org/wiki/Rolladen_Schneider_LS10

**Comment by samuel-git** [comment]
Is fixed, should be online in the coming days.

**Comment by UniformPapa** [comment]
Unfortunately the issue is NOT closed.
The 15M version of LS 10-st is now shown as powered glider (symbol Zapfsäule) but the 18M version of LS 10-st is still wrong in the database.

**Comment by flyingjoe** [comment]
@UniformPapa Thanks for bringing this up again! It was fixed in our gliderlist but never imported to the server. It's fixed now.
